build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 100
    excludes:
      - '**/test/**'
      - '**/commonTest/**'
      - '**/androidTest/**'
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 12
    ignoreAnnotated:
      - 'Composable'
  CyclomaticComplexMethod:
    threshold: 20
  NestedBlockDepth:
    threshold: 5
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 20
    thresholdInEnums: 15
  ComplexCondition:
    threshold: 5

exceptions:
  TooGenericExceptionThrown:
    active: true
    excludes:
      - '**/test/**'
      - '**/commonTest/**'
      - '**/androidTest/**'
  TooGenericExceptionCaught:
    active: true
    excludes:
      - '**/test/**'
      - '**/commonTest/**'
      - '**/androidTest/**'

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  UseCheckOrError:
    active: false

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
